# Use official Node.js image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy source files
COPY . .


# Expose app port
EXPOSE 3000

# Start server
CMD ["node", "server.js"]
